spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400


cloud:
  aws:
    s3:
      bucket: bloo-image-store
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIASP6HEPETDVQOERUQ
      secretKey: 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
    stack:
      auto: false
